### ISSUE TITLE
Fix wrong counting of blog articles

### ISSUE THREAD

**Issue by kftw** [tollwerk/TYPO3-ext-tw_blog#8]
Right now the blog list always counts **all** blog articles found in the **entire TYPO3 pagetree**, no matter where they are. So if we want a blog list to show just articles from a certain folder / page, the count is wrong, possibly leading to unexpected behaviour of the page browser.

**Comment by jkphl** [comment]
Commit c31d8da (TYPO3 10.x branch) fixes this and should be applicable by cherry picking
